### ISSUE TITLE
Support for trailing commas

### ISSUE THREAD

**Issue by ahaverty** [SBeator/sort-js-object-keys#14]
The extension is removing trailing commas after sorting an object.
We use the [tslint rule for trailing commas](https://palantir.github.io/tslint/rules/trailing-comma/), which is great when it comes to new additions to an object when viewing in PRs/version control.
It's not an official rule, therefore I assume it should be an option in this extension if it was implemented.
We're in a typescript/nodejs environment.

**Comment by ahaverty** [comment]
I've noticed the readme seems to actually add a trailing comma in the example, perhaps this is a bug?: 
![readme](https://github.com/SBeator/sort-js-object-keys/raw/master/images/usage.gif)

**Comment by SBeator** [comment]
@ahaverty thanks for this feedback, actually this was a feature in the previous version (0.0.x). 

But after the version 1.0.0, the previous logic has some conflicts with some other main logic, so I removed it.

I think an easy way for you is that you can use any code formatter plugin in vs code like __prettier__ to help you format this.

 Anyway, thanks for you feedback and I will see if I can add this feature back in future.

**Comment by ahaverty** [comment]
@SBeator Prettier extension with `"trailingComma": "all"` does the trick after formatting, nice workaround!

**Comment by SBeator** [comment]
If your problem is resolved, I will close this issue.
