### ISSUE TITLE
JSS keys

### ISSUE THREAD

**Issue by StevePotter** [SBeator/sort-js-object-keys#3]
Hi, I am using your great plugin to sort jss objects, which are just JS objects but with a few funny key names.  This should be sortable:
```
{
    backgroundColor: 'transparent',
    color: GRAY_TEXT,
    fontSize: '0.8em',
    '&:hover': {
      color: SECONDARY,
    },
  }
```

But the plugin fails.  If I remove the `&:hover` key then it's fine.  If I can help fix this, please let me know

**Comment by SBeator** [comment]
It is because there is a ":" in the key '&:hover', and it make my regex doesn't work. 
I will try to update my regex to support this feature.

**Comment by SBeator** [comment]
This feature is supported in the latest version
