### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by alexichepura** [SBeator/sort-js-object-keys#5]
Hello,
thx for the extension!

Trying to use it in typescript only leads to a warning.
`Please make sure your selected text is a JS object!`

Can it support TypeScript?
Thanks :)

**Comment by chrisdopuch** [comment]
👍 Good idea, this plugin is so useful for TypeScript because it by default wants you to sort the keys of your object literals!

**Comment by SBeator** [comment]
@chrisdopuch, 
When you said it by default want this feature, do you mean the [object-literal-sort-keys](https://palantir.github.io/tslint/rules/object-literal-sort-keys/) in tslint?

**Comment by chrisdopuch** [comment]
Yes tslint by default requires sorted keys, not typescript, that's right @SBeator

**Comment by SBeator** [comment]
@chrisdopuch Thanks for you feedback, but could you please provide me more details about your usage?

I wrote some TS code and my usage of the object is the same as the JS object.
e.g: This is the object in my TS code:
```
const initState = {
  name: '',
  id: 0,
  chineseName: '',
  firstName: '',
  lastName: '',
  stores: [{}],
};
```
My plugin works for this usage. 

Actually, the reason why I want to create this plugin is because I am already using object-literal-sort-keys in tslint in my project. But it works well in my TS project.

Could you please provide me some test cases and I can understand what other scenarios I need to support?

**Comment by chrisdopuch** [comment]
Oh @SBeator sorry yes I should be more specific. Here's an example test case of what I was running into: 
```interface IPerson {
  name: string;
}

const data = {
  person: { name: 'Jill' } as IPerson,
};```

If you try to sort the `data` object literal it will error out with "Please make sure your selected text is a JS object"

**Comment by SBeator** [comment]
@chrisdopuch 
Oh, I can understand your use case. 
Thanks for you feedback and I will try to update this plugin to support this new feature if I have time :)

**Comment by SBeator** [comment]
@chrisdopuch I have updated the plugin to support typescript. 
Please update it and have a try. 

Now, this TS object:
 ```typescript
    {
        user: {
          name: 'Xingxin',
          age: 26
        } as IPerson,
        date: '02/03/2018' as any,
        message: 'this is message',
        password: '****' as IPassword
    }
  ```
  Will be formated to:
  ```typescript
    {
        date: ('02/03/2018' as any),
        message: 'this is message',
        password: ('****' as IPassword),
        user: ({
            name: 'Xingxin',
            age: 26
        } as IPerson)
    }
  ```

Please let me know if this feature works for you.

**Comment by chris-dopuch** [comment]
Nice job @SBeator that works on my end too! Thank you so much

**Comment by alexichepura** [comment]
@SBeator thank you! Works well for me.
Another question. Can it support interfaces and types? If yes, let's create another issue ;)
