### ISSUE TITLE
Request: support ES6 spread syntax

### ISSUE THREAD

**Issue by chris-dopuch** [SBeator/sort-js-object-keys#7]
Hello again!

I've been using this tool in VSCode a lot and it's great!

I ran into another edge case, this time with ES6 object spread syntax.
Here is an example that will cause it to fail:

```
const otherObj = {};

const obj = {
  ...otherObj,
  a: 'a',
  b: 'b'
};
```

**Comment by SBeator** [comment]
@chris-dopuch 
Thanks for your feedback, I will mark this as a feature and try to implement it when I am free. 
Of course I will be very happy if you can help send PR for this change

**Comment by SBeator** [comment]
Added this feature in PR #13
